# Generated by Django 3.2.12 on 2022-04-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_choice', models.CharField(max_length=1000)),
                ('age', models.CharField(max_length=1000)),
            ],
        ),
    ]
